# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x06\x63ommon\"%\n\x12ReplicationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x13ReplicationResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.common.Status*:\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x32\x61\n\x12ReplicationService\x12K\n\x10ReplicateMessage\x12\x1a.common.ReplicationRequest\x1a\x1b.common.ReplicationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=123
  _globals['_STATUS']._serialized_end=181
  _globals['_REPLICATIONREQUEST']._serialized_start=29
  _globals['_REPLICATIONREQUEST']._serialized_end=66
  _globals['_REPLICATIONRESPONSE']._serialized_start=68
  _globals['_REPLICATIONRESPONSE']._serialized_end=121
  _globals['_REPLICATIONSERVICE']._serialized_start=183
  _globals['_REPLICATIONSERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
