import os

SECONDARY_ADDRESSES = os.getenv("SECONDARY_ADDRESSES").split(",") if "SECONDARY_ADDRESSES" in os.environ else ["localhost:50051"]
HEARTBEAT_INTERVAL_SEC = os.getenv("HEARTBEAT_INTERVAL_SEC", 5)
HEARTBEAT_TIMEOUT_SEC = os.getenv("HEARTBEAT_TIMEOUT_SEC", 10)
HEARTBEAT_FAILURE_THRESHOLD = os.getenv("HEARTBEAT_FAILURE_THRESHOLD", 2)